Name:           ros-indigo-ntpd-driver
Version:        1.2.0
Release:        1%{?dist}
Summary:        ROS ntpd_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/ntpd_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       poco-devel
Requires:       ros-indigo-cmake-modules
Requires:       ros-indigo-message-generation
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
BuildRequires:  poco-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-message-runtime
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-sensor-msgs

%description
ntpd_driver sends TimeReference message time to ntpd server

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Mar 28 2016 Vladimir Ermakov <vooon341@gmail.com> - 1.2.0-1
- Autogenerated by Bloom

* Fri Oct 02 2015 Vladimir Ermakov <vooon341@gmail.com> - 1.2.0-0
- Autogenerated by Bloom

* Sat Jul 18 2015 Vladimir Ermakov <vooon341@gmail.com> - 1.1.1-0
- Autogenerated by Bloom

* Fri Apr 17 2015 Vladimir Ermakov <vooon341@gmail.com> - 1.1.0-0
- Autogenerated by Bloom

* Sat Jan 24 2015 Vladimir Ermakov <vooon341@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

